INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");
INSERT INTO users(name) VALUES ("Tim");

INSERT INTO projects(title) VALUES ("Project Name");
INSERT INTO projects(title) VALUES ("Project Name");
INSERT INTO projects(title) VALUES ("Project Name");
INSERT INTO projects(title) VALUES ("Project Name");
INSERT INTO projects(title) VALUES ("Project Name");
INSERT INTO projects(title) VALUES ("Project Name");
INSERT INTO projects(title) VALUES ("Project Name");
INSERT INTO projects(title) VALUES ("Project Name");
INSERT INTO projects(title) VALUES ("Project Name");
INSERT INTO projects(title) VALUES ("Project Name");

INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
INSERT INTO pledges(amount) VALUES ("30");
